name: Kubegres CI

on:
  push:
    branches: [main, github]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Kubegres Tests in Kind
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.22.0

      - name: Export KUBECONFIG
        run: echo "KUBECONFIG=${HOME}/.kube/config" >> $GITHUB_ENV

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Install CRDs and Deploy Kubegres
        run: |
          make install
          make deploy IMG=reactivetechio/kubegres

      - name: Wait for Kubegres controller to be ready
        run: kubectl rollout status deployment/kubegres-controller -n kubegres-system --timeout=90s

      - name: Run Tests
        run: make test

      - name: Delete Kind cluster (cleanup)
        if: always()
        run: kind delete cluster
